import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:path_provider/path_provider.dart';
import 'dart:io';

class CVScreen extends StatefulWidget {
  const CVScreen({super.key});

  @override
  State<CVScreen> createState() => _CVScreenState();
}

class _CVScreenState extends State<CVScreen> {
  final _nameCtrl = TextEditingController();
  final _dobCtrl = TextEditingController();
  final _phoneCtrl = TextEditingController();
  final _emailCtrl = TextEditingController();
  final _addressCtrl = TextEditingController();
  final _jobCtrl = TextEditingController();
  final _objectiveCtrl = TextEditingController();
  final _educationCtrl = TextEditingController();
  final _skillsCtrl = TextEditingController();
  final _experienceCtrl = TextEditingController();
  final _languagesCtrl = TextEditingController();

  bool _cvGenerated = false;
  String _cvContent = '';

  void _generateCV() {
    if (_nameCtrl.text.trim().isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Naam zaroori hai!')));
      return;
    }

    final cv = '''
╔══════════════════════════════════════════╗
║           CURRICULUM VITAE               ║
╚══════════════════════════════════════════╝

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  ${_nameCtrl.text.trim().toUpperCase()}
  ${_jobCtrl.text.trim().isNotEmpty ? _jobCtrl.text.trim() : 'Professional'}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

📋 PERSONAL INFORMATION
─────────────────────────
• Full Name    : ${_nameCtrl.text.trim()}
• Date of Birth: ${_dobCtrl.text.trim().isNotEmpty ? _dobCtrl.text.trim() : 'N/A'}
• Phone        : ${_phoneCtrl.text.trim().isNotEmpty ? _phoneCtrl.text.trim() : 'N/A'}
• Email        : ${_emailCtrl.text.trim().isNotEmpty ? _emailCtrl.text.trim() : 'N/A'}
• Address      : ${_addressCtrl.text.trim().isNotEmpty ? _addressCtrl.text.trim() : 'N/A'}

🎯 OBJECTIVE
─────────────────────────
${_objectiveCtrl.text.trim().isNotEmpty ? _objectiveCtrl.text.trim() : 'To obtain a challenging position where I can utilize my skills and contribute to the organization\'s growth.'}

🎓 EDUCATION
─────────────────────────
${_educationCtrl.text.trim().isNotEmpty ? _educationCtrl.text.trim() : 'Please add your education details.'}

💼 EXPERIENCE
─────────────────────────
${_experienceCtrl.text.trim().isNotEmpty ? _experienceCtrl.text.trim() : 'Fresher / No experience yet.'}

⚡ SKILLS
─────────────────────────
${_skillsCtrl.text.trim().isNotEmpty ? _skillsCtrl.text.trim().split(',').map((s) => '• ${s.trim()}').join('\n') : '• Please add your skills'}

🌐 LANGUAGES
─────────────────────────
${_languagesCtrl.text.trim().isNotEmpty ? _languagesCtrl.text.trim().split(',').map((s) => '• ${s.trim()}').join('\n') : '• Hindi\n• English'}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Generated by CodeCraft AI
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
''';

    setState(() {
      _cvContent = cv;
      _cvGenerated = true;
    });
  }

  Future<void> _downloadCV() async {
    try {
      final dir = await getApplicationDocumentsDirectory();
      final file = File('${dir.path}/${_nameCtrl.text.trim()}_CV.txt');
      await file.writeAsString(_cvContent);

      if (mounted) {
        showDialog(
          context: context,
          builder: (ctx) => AlertDialog(
            backgroundColor: const Color(0xFF12122A),
            title: const Text('CV Saved! ✅',
                style: TextStyle(color: Colors.white)),
            content: Column(
              mainAxisSize: MainAxisSize.min,
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                const Text('CV is file mein save hua:',
                    style: TextStyle(color: Colors.grey)),
                const SizedBox(height: 8),
                Text(file.path,
                    style: const TextStyle(
                        color: Color(0xFF6C63FF), fontSize: 11)),
              ],
            ),
            actions: [
              TextButton(
                onPressed: () {
                  Clipboard.setData(ClipboardData(text: _cvContent));
                  Navigator.pop(ctx);
                  ScaffoldMessenger.of(context).showSnackBar(const SnackBar(
                      content: Text('CV clipboard mein copy ho gaya!')));
                },
                child: const Text('Copy karo',
                    style: TextStyle(color: Color(0xFF3ECFCF))),
              ),
              TextButton(
                onPressed: () => Navigator.pop(ctx),
                child: const Text('OK',
                    style: TextStyle(color: Color(0xFF6C63FF))),
              ),
            ],
          ),
        );
      }
    } catch (e) {
      ScaffoldMessenger.of(context)
          .showSnackBar(SnackBar(content: Text('Error: $e')));
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(0xFF0A0A14),
      appBar: AppBar(
        backgroundColor: const Color(0xFF12122A),
        title: const Row(
          children: [
            Icon(Icons.description, color: Color(0xFF6C63FF)),
            SizedBox(width: 10),
            Text('CV Generator',
                style: TextStyle(
                    color: Colors.white, fontWeight: FontWeight.bold)),
          ],
        ),
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16),
        child: Column(
          children: [
            _buildSection('👤 Personal Info', [
              _field(_nameCtrl, 'Full Name *', Icons.person),
              _field(_dobCtrl, 'Date of Birth (DD/MM/YYYY)', Icons.cake),
              _field(_phoneCtrl, 'Phone Number', Icons.phone),
              _field(_emailCtrl, 'Email Address', Icons.email),
              _field(_addressCtrl, 'Address / City', Icons.location_on),
              _field(_jobCtrl, 'Job Title / Profession', Icons.work),
            ]),
            const SizedBox(height: 12),
            _buildSection('🎯 Objective', [
              _fieldMulti(_objectiveCtrl, 'Career objective likho...'),
            ]),
            const SizedBox(height: 12),
            _buildSection('🎓 Education', [
              _fieldMulti(_educationCtrl,
                  'e.g. B.Tech Computer Science, ABC College, 2022'),
            ]),
            const SizedBox(height: 12),
            _buildSection('💼 Experience', [
              _fieldMulti(_experienceCtrl,
                  'e.g. Software Developer at XYZ Company, 2022-2023'),
            ]),
            const SizedBox(height: 12),
            _buildSection('⚡ Skills', [
              _fieldMulti(_skillsCtrl,
                  'Comma se alag karo: Flutter, Python, Java, etc.'),
            ]),
            const SizedBox(height: 12),
            _buildSection('🌐 Languages', [
              _fieldMulti(
                  _languagesCtrl, 'e.g. Hindi, English, Marathi'),
            ]),
            const SizedBox(height: 20),

            // Generate Button
            GestureDetector(
              onTap: _generateCV,
              child: Container(
                width: double.infinity,
                padding: const EdgeInsets.symmetric(vertical: 14),
                decoration: BoxDecoration(
                  gradient: const LinearGradient(
                      colors: [Color(0xFF6C63FF), Color(0xFF3ECFCF)]),
                  borderRadius: BorderRadius.circular(12),
                ),
                child: const Center(
                  child: Row(
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: [
                      Icon(Icons.auto_awesome, color: Colors.white),
                      SizedBox(width: 8),
                      Text('CV Generate Karo',
                          style: TextStyle(
                              color: Colors.white,
                              fontWeight: FontWeight.bold,
                              fontSize: 16)),
                    ],
                  ),
                ),
              ),
            ),

            if (_cvGenerated) ...[
              const SizedBox(height: 16),

              // CV Preview
              Container(
                width: double.infinity,
                padding: const EdgeInsets.all(16),
                decoration: BoxDecoration(
                  color: const Color(0xFF12122A),
                  border: Border.all(
                      color: const Color(0xFF6C63FF).withOpacity(0.5)),
                  borderRadius: BorderRadius.circular(12),
                ),
                child: Text(
                  _cvContent,
                  style: const TextStyle(
                    color: Colors.white70,
                    fontSize: 12,
                    fontFamily: 'monospace',
                    height: 1.5,
                  ),
                ),
              ),
              const SizedBox(height: 12),

              Row(
                children: [
                  Expanded(
                    child: GestureDetector(
                      onTap: () {
                        Clipboard.setData(ClipboardData(text: _cvContent));
                        ScaffoldMessenger.of(context).showSnackBar(
                            const SnackBar(
                                content: Text('CV copy ho gaya!')));
                      },
                      child: Container(
                        padding: const EdgeInsets.symmetric(vertical: 12),
                        decoration: BoxDecoration(
                          color: const Color(0xFF12122A),
                          border: Border.all(color: const Color(0xFF6C63FF)),
                          borderRadius: BorderRadius.circular(10),
                        ),
                        child: const Center(
                          child: Row(
                            mainAxisAlignment: MainAxisAlignment.center,
                            children: [
                              Icon(Icons.copy,
                                  color: Color(0xFF6C63FF), size: 18),
                              SizedBox(width: 6),
                              Text('Copy',
                                  style:
                                      TextStyle(color: Color(0xFF6C63FF))),
                            ],
                          ),
                        ),
                      ),
                    ),
                  ),
                  const SizedBox(width: 10),
                  Expanded(
                    child: GestureDetector(
                      onTap: _downloadCV,
                      child: Container(
                        padding: const EdgeInsets.symmetric(vertical: 12),
                        decoration: BoxDecoration(
                          gradient: const LinearGradient(
                              colors: [Color(0xFF6C63FF), Color(0xFF3ECFCF)]),
                          borderRadius: BorderRadius.circular(10),
                        ),
                        child: const Center(
                          child: Row(
                            mainAxisAlignment: MainAxisAlignment.center,
                            children: [
                              Icon(Icons.download,
                                  color: Colors.white, size: 18),
                              SizedBox(width: 6),
                              Text('Save',
                                  style: TextStyle(color: Colors.white)),
                            ],
                          ),
                        ),
                      ),
                    ),
                  ),
                ],
              ),
            ],
          ],
        ),
      ),
    );
  }

  Widget _buildSection(String title, List<Widget> children) {
    return Container(
      padding: const EdgeInsets.all(14),
      decoration: BoxDecoration(
        color: const Color(0xFF12122A),
        border: Border.all(color: const Color(0xFF6C63FF).withOpacity(0.2)),
        borderRadius: BorderRadius.circular(12),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(title,
              style: const TextStyle(
                  color: Color(0xFF6C63FF),
                  fontWeight: FontWeight.bold,
                  fontSize: 14)),
          const SizedBox(height: 10),
          ...children,
        ],
      ),
    );
  }

  Widget _field(TextEditingController ctrl, String hint, IconData icon) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 8),
      child: TextField(
        controller: ctrl,
        style: const TextStyle(color: Colors.white, fontSize: 14),
        decoration: InputDecoration(
          hintText: hint,
          hintStyle: const TextStyle(color: Colors.grey, fontSize: 13),
          prefixIcon: Icon(icon, color: const Color(0xFF6C63FF), size: 18),
          filled: true,
          fillColor: const Color(0xFF0A0A14),
          border: OutlineInputBorder(
              borderRadius: BorderRadius.circular(10),
              borderSide: BorderSide.none),
          enabledBorder: OutlineInputBorder(
            borderRadius: BorderRadius.circular(10),
            borderSide:
                BorderSide(color: const Color(0xFF6C63FF).withOpacity(0.2)),
          ),
          focusedBorder: OutlineInputBorder(
            borderRadius: BorderRadius.circular(10),
            borderSide: const BorderSide(color: Color(0xFF6C63FF)),
          ),
          contentPadding:
              const EdgeInsets.symmetric(horizontal: 12, vertical: 12),
        ),
      ),
    );
  }

  Widget _fieldMulti(TextEditingController ctrl, String hint) {
    return TextField(
      controller: ctrl,
      style: const TextStyle(color: Colors.white, fontSize: 13),
      maxLines: 3,
      decoration: InputDecoration(
        hintText: hint,
        hintStyle: const TextStyle(color: Colors.grey, fontSize: 12),
        filled: true,
        fillColor: const Color(0xFF0A0A14),
        border: OutlineInputBorder(
            borderRadius: BorderRadius.circular(10),
            borderSide: BorderSide.none),
        enabledBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(10),
          borderSide:
              BorderSide(color: const Color(0xFF6C63FF).withOpacity(0.2)),
        ),
        focusedBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(10),
          borderSide: const BorderSide(color: Color(0xFF6C63FF)),
        ),
      ),
    );
  }
}
